### ISSUE TITLE
compilation fails with kernel 4.13.11

### ISSUE THREAD

**Issue by HJarausch** [lanconnected/EnhanceIO#28]
There must have been some changes in the kernel recently.
Are there any patches, yet?
Many thanks,
Helmut.

Trying to compile EnhanceIO I get

In file included from /Temp/enhanceio/eio.h:64:0,
                 from /Temp/enhanceio/eio_main.c:37:
/Temp/enhanceio/eio_main.c: In function 'bc_put':
/Temp/enhanceio/compat.h:288:38: error: 'struct bio' has no member named 'bi_error'; did you mean 'bi_iter'?
 #define EIO_BIO_ENDIO(B,E) do { (B)->bi_error = E; bio_endio(B); } while (0)
                                      ^
/Temp/enhanceio/eio_main.c:110:3: note: in expansion of macro 'EIO_BIO_ENDIO'
   EIO_BIO_ENDIO(bc->bc_bio, bc->bc_error);
   ^~~~~~~~~~~~~
/Temp/enhanceio/eio_main.c: In function 'eio_map':
/Temp/enhanceio/compat.h:288:38: error: 'struct bio' has no member named 'bi_error'; did you mean 'bi_iter'?
 #define EIO_BIO_ENDIO(B,E) do { (B)->bi_error = E; bio_endio(B); } while (0)
                                      ^
/Temp/enhanceio/eio_main.c:2395:3: note: in expansion of macro 'EIO_BIO_ENDIO'
   EIO_BIO_ENDIO(bio, 0);
   ^~~~~~~~~~~~~
/Temp/enhanceio/compat.h:288:38: error: 'struct bio' has no member named 'bi_error'; did you mean 'bi_iter'?
 #define EIO_BIO_ENDIO(B,E) do { (B)->bi_error = E; bio_endio(B); } while (0)
                                      ^
/Temp/enhanceio/eio_main.c:2403:4: note: in expansion of macro 'EIO_BIO_ENDIO'
    EIO_BIO_ENDIO(bio, -EPERM);
    ^~~~~~~~~~~~~
/Temp/enhanceio/compat.h:288:38: error: 'struct bio' has no member named 'bi_error'; did you mean 'bi_iter'?
 #define EIO_BIO_ENDIO(B,E) do { (B)->bi_error = E; bio_endio(B); } while (0)
                                      ^
/Temp/enhanceio/eio_main.c:2430:3: note: in expansion of macro 'EIO_BIO_ENDIO'
   EIO_BIO_ENDIO(bio, -ENODEV);
   ^~~~~~~~~~~~~
/Temp/enhanceio/compat.h:288:38: error: 'struct bio' has no member named 'bi_error'; did you mean 'bi_iter'?
 #define EIO_BIO_ENDIO(B,E) do { (B)->bi_error = E; bio_endio(B); } while (0)
                                      ^
/Temp/enhanceio/eio_main.c:2460:3: note: in expansion of macro 'EIO_BIO_ENDIO'
   EIO_BIO_ENDIO(bio, -ENOMEM);
   ^~~~~~~~~~~~~
/Temp/enhanceio/compat.h:288:38: error: 'struct bio' has no member named 'bi_error'; did you mean 'bi_iter'?
 #define EIO_BIO_ENDIO(B,E) do { (B)->bi_error = E; bio_endio(B); } while (0)
                                      ^
/Temp/enhanceio/eio_main.c:2486:4: note: in expansion of macro 'EIO_BIO_ENDIO'
    EIO_BIO_ENDIO(bio, ret);
    ^~~~~~~~~~~~~

**Comment by lanconnected** [comment]
Yep, they renamed bi_error to bi_status in 4.13. They had a good reason for it, surely. I'll add compat soon (hope not to fall to some other caveat). Thanks for reporting.

**Comment by lanconnected** [comment]
Linus has a nice comment about those changes: https://www.spinics.net/lists/linux-block/msg15027.html

**Comment by HJarausch** [comment]
I'm trying to fix this myself. But there seems to be another caveat.
The type of the error code(s) has been changed from  int  to blk_status_t which is
 typedef u8 __bitwise blk_status_t;    (linux/blk_types.h)

That's a problem if the error code was negative. Furthermore the symbolic names of the error codes have changed.

**Comment by HJarausch** [comment]
[EnhanceIO_Kernel4_13.patch.zip](https://github.com/lanconnected/EnhanceIO/files/1455006/EnhanceIO_Kernel4_13.patch.zip)
Hi,
I think I have fixed EnhanceIO for the 4.13 kernel (here 4.13.11) and the utility eio_cli for using Python3.
Since I'm completely new to EnhanceIO, I have to ask a 'dumb' question:
How to use it?
I have
./eio_cli info
Cache Name       : Test_Cache
Source Device    : /dev/sda1
SSD Device       : /dev/nvme0n1p3
Policy           : lru
Mode             : Write Back
Block Size       : 4096
Associativity    : 256
State            : normal

Do I have to mount a file system?
I've tried to mount /dev/nvme0n1p3 but it failed due to /dev/nvme0n1p3 already mounted or mount point busy
The FS /dev/sda1 has been mounted before I've created the cache.

So, I cannot not test if it's working, yet.
Anyway, I attach my changes here.
Thanks for EnhanceIO,
Helmut

**Comment by lanconnected** [comment]
resolved in https://github.com/lanconnected/EnhanceIO/commit/7518ec395d844b0163ed1e7dd9773f4b4559e92b

**Comment by lanconnected** [comment]
EIO is completely transparent, you can create/edit/delete cache regardless of source device is mounted or not. New device is not created when you create cache, cache just "magically" starts working for source device.

**Comment by lanconnected** [comment]
Please close this bug again if the latest commit compiles for you.

**Comment by HJarausch** [comment]
[EnhanceIO_Kernel4_13.patch.zip](https://github.com/lanconnected/EnhanceIO/files/1455006/EnhanceIO_Kernel4_13.patch.zip)
Hi,
I think I have fixed EnhanceIO for the 4.13 kernel (here 4.13.11) and the utility eio_cli for using Python3.
Since I'm completely new to EnhanceIO, I have to ask a 'dumb' question:
How to use it?
I have
./eio_cli info
Cache Name       : Test_Cache
Source Device    : /dev/sda1
SSD Device       : /dev/nvme0n1p3
Policy           : lru
Mode             : Write Back
Block Size       : 4096
Associativity    : 256
State            : normal

Do I have to mount a file system?
I've tried to mount /dev/nvme0n1p3 but it failed due to /dev/nvme0n1p3 already mounted or mount point busy
The FS /dev/sda1 has been mounted before I've created the cache.

So, I cannot not test if it's working, yet.
Anyway, I attach my changes here.
Thanks for EnhanceIO,
Helmut

**Comment by HJarausch** [comment]
I'm sorry, but your version doesn't compile here.
I still get
In file included from /home/jarausch/GenToo/Src/EnhanceIO_NEW/Driver/enhanceio/eio.h:64:0,
                 from /home/jarausch/GenToo/Src/EnhanceIO_NEW/Driver/enhanceio/eio_main.c:37:
/home/jarausch/GenToo/Src/EnhanceIO_NEW/Driver/enhanceio/eio_main.c: In function 'bc_put':
/home/jarausch/GenToo/Src/EnhanceIO_NEW/Driver/enhanceio/compat.h:293:38: error: 'struct bio' has no member named 'bi_error'; did you mean 'bi_iter'?
 #define EIO_BIO_ENDIO(B,E) do { (B)->bi_error = E; bio_endio(B); } while (0)
                                      ^
/home/jarausch/GenToo/Src/EnhanceIO_NEW/Driver/enhanceio/eio_main.c:110:3: note: in expansion of macro 'EIO_BIO_ENDIO'
   EIO_BIO_ENDIO(bc->bc_bio, bc->bc_error);
   ^~~~~~~~~~~~~
/home/jarausch/GenToo/Src/EnhanceIO_NEW/Driver/enhanceio/eio_main.c: In function 'eio_map':
/home/jarausch/GenToo/Src/EnhanceIO_NEW/Driver/enhanceio/compat.h:293:38: error: 'struct bio' has no member named 'bi_error'; did you mean 'bi_iter'?
 #define EIO_BIO_ENDIO(B,E) do { (B)->bi_error = E; bio_endio(B); } while (0)
                                      ^
/home/jarausch/GenToo/Src/EnhanceIO_NEW/Driver/enhanceio/eio_main.c:2395:3: note: in expansion of macro 'EIO_BIO_ENDIO'
   EIO_BIO_ENDIO(bio, 0);
   ^~~~~~~~~~~~~
/home/jarausch/GenToo/Src/EnhanceIO_NEW/Driver/enhanceio/compat.h:293:38: error: 'struct bio' has no member named 'bi_error'; did you mean 'bi_iter'?
 #define EIO_BIO_ENDIO(B,E) do { (B)->bi_error = E; bio_endio(B); } while (0)
                                      ^
/home/jarausch/GenToo/Src/EnhanceIO_NEW/Driver/enhanceio/eio_main.c:2403:4: note: in expansion of macro 'EIO_BIO_ENDIO'
    EIO_BIO_ENDIO(bio, -EPERM);
    ^~~~~~~~~~~~~
/home/jarausch/GenToo/Src/EnhanceIO_NEW/Driver/enhanceio/compat.h:293:38: error: 'struct bio' has no member named 'bi_error'; did you mean 'bi_iter'?
 #define EIO_BIO_ENDIO(B,E) do { (B)->bi_error = E; bio_endio(B); } while (0)
                                      ^
/home/jarausch/GenToo/Src/EnhanceIO_NEW/Driver/enhanceio/eio_main.c:2430:3: note: in expansion of macro 'EIO_BIO_ENDIO'
   EIO_BIO_ENDIO(bio, -ENODEV);
   ^~~~~~~~~~~~~
/home/jarausch/GenToo/Src/EnhanceIO_NEW/Driver/enhanceio/compat.h:293:38: error: 'struct bio' has no member named 'bi_error'; did you mean 'bi_iter'?
 #define EIO_BIO_ENDIO(B,E) do { (B)->bi_error = E; bio_endio(B); } while (0)
                                      ^
/home/jarausch/GenToo/Src/EnhanceIO_NEW/Driver/enhanceio/eio_main.c:2460:3: note: in expansion of macro 'EIO_BIO_ENDIO'
   EIO_BIO_ENDIO(bio, -ENOMEM);
   ^~~~~~~~~~~~~
/home/jarausch/GenToo/Src/EnhanceIO_NEW/Driver/enhanceio/compat.h:293:38: error: 'struct bio' has no member named 'bi_error'; did you mean 'bi_iter'?
 #define EIO_BIO_ENDIO(B,E) do { (B)->bi_error = E; bio_endio(B); } while (0)
                                      ^
/home/jarausch/GenToo/Src/EnhanceIO_NEW/Driver/enhanceio/eio_main.c:2486:4: note: in expansion of macro 'EIO_BIO_ENDIO'
    EIO_BIO_ENDIO(bio, ret);


What do think about my patch?
I am away for two days now.
Thanks,
Helmut

**Comment by lanconnected** [comment]
oops, my bad. Should be repaired in latest commit, please give it a try. https://github.com/lanconnected/EnhanceIO/commit/bbeab3d55ea4aa5d316a16c5d10f5897fa460728

**Comment by lanconnected** [comment]
Helmut, does last commit compile for you? Please close the bug then. Your patch contains eio_cli changes as well, if there is a problem in current eio_cli with python3, please open a new bug with proposed changes. Thanks!
